logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: springsecuritytest3
    root_packages: com.app.springsecuritytest3
server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/liquibase_changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false
eclipselink:
   ddl:
       auto:
            create:
                   delete: false
jwt:
  secret: replicacia
